### ISSUE TITLE
[1.10.2] crash on start

### ISSUE THREAD

**Issue by Cat-McCatface** [Tamaized/TamModized#8]
I would put something here on how to reproduce it but I'm a sad panda.

Forge: 2107
TamModized-1.10.2-0.2.2
VoidCraft-1.10.2-0.9.8
[crash-2016-10-22_05.33.12-client.txt](https://github.com/Tamaized/TamModized/files/545732/crash-2016-10-22_05.33.12-client.txt)

**Comment by Tamaized** [comment]
Use TamModized version 0.2.4
